# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/jstik.xdc

# Block Designs: bd/jsk_top/jsk_top.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==jsk_top || ORIG_REF_NAME==jsk_top} -quiet] -quiet

# IP: bd/jsk_top/ip/jsk_top_axi4stream_spi_master_0_0/jsk_top_axi4stream_spi_master_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==jsk_top_axi4stream_spi_master_0_0 || ORIG_REF_NAME==jsk_top_axi4stream_spi_master_0_0} -quiet] -quiet

# IP: bd/jsk_top/ip/jsk_top_AXI4Stream_UART_0_0/jsk_top_AXI4Stream_UART_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==jsk_top_AXI4Stream_UART_0_0 || ORIG_REF_NAME==jsk_top_AXI4Stream_UART_0_0} -quiet] -quiet

# IP: bd/jsk_top/ip/jsk_top_clk_wiz_0_0/jsk_top_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==jsk_top_clk_wiz_0_0 || ORIG_REF_NAME==jsk_top_clk_wiz_0_0} -quiet] -quiet

# IP: bd/jsk_top/ip/jsk_top_proc_sys_reset_0_0/jsk_top_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==jsk_top_proc_sys_reset_0_0 || ORIG_REF_NAME==jsk_top_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/jsk_top/ip/jsk_top_jstk_uart_bridge_0_0/jsk_top_jstk_uart_bridge_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==jsk_top_jstk_uart_bridge_0_0 || ORIG_REF_NAME==jsk_top_jstk_uart_bridge_0_0} -quiet] -quiet

# IP: bd/jsk_top/ip/jsk_top_digilent_jstk2_0_0/jsk_top_digilent_jstk2_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==jsk_top_digilent_jstk2_0_0 || ORIG_REF_NAME==jsk_top_digilent_jstk2_0_0} -quiet] -quiet

# XDC: k:/Z01_ArchiveProj/00_Project/03_DESD/07_LAB2/01_proj/jstkLab2/jstkLab2.gen/sources_1/bd/jsk_top/jsk_top_ooc.xdc
